# Generated by Django 5.2.17 on 2026-10-03 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('beaches', 'Beaches'), ('hills', 'Hills'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('adventure', 'Adventure'), ('pilgrimage', 'Pilgrimage'), ('international', 'International')], max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='destinations/')),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('food_details', models.CharField(blank=True, max_length=200)),
                ('room_type', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='hotels/')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('available', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Room charge per day')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('family', 'Family'), ('honeymoon', 'Honeymoon'), ('adventure', 'Adventure'), ('budget', 'Budget'), ('luxury', 'Luxury')], default='family', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('destination', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Charge per member')),
                ('duration', models.CharField(help_text='e.g. 4 days / 3 nights', max_length=50)),
                ('start_date', models.DateField()),
                ('seats', models.PositiveIntegerField(default=10)),
                ('available', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, upload_to='packages/')),
                ('image2', models.ImageField(blank=True, upload_to='packages/')),
                ('image3', models.ImageField(blank=True, upload_to='packages/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car (4 seater)'), ('SUV', 'SUV (6 seater)'), ('TEMPO', 'Tempo traveller (12 seater)'), ('BUS', 'Tourist bus (30 seater)'), ('BIKE', 'Bike / scooter (2 seater)')], max_length=5)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='vehicles/')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Vehicles available')),
                ('driver_included', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount per day')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trip', 'Trip'), ('package', 'Tour package'), ('vehicle', 'Vehicle'), ('hotel', 'Hotel')], max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('members', models.PositiveIntegerField(default=1, help_text='Members (packages) or days (vehicles/hotels)')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='feedback/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('txn_id', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='profiles/')),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per night')),
                ('photo', models.ImageField(blank=True, upload_to='rooms/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'package')},
            },
        ),
    ]
